export const ERROR_CODES = [
  'MISSING_PRUNA_KEY', 'PRUNA_API_ERROR', 'PRUNA_PREDICTION_FAILED', 'PRUNA_RUN_ABANDONED',
  'POLLEN_KEY_REQUIRED', 'POLLEN_INSUFFICIENT', 'POLLEN_SERVER_BUDGET',
  'POLLEN_MODEL_NOT_ALLOWED', 'POLLEN_MODEL_NOT_ALLOWED_OWN_KEY',
  'PROVIDER_UNAVAILABLE', 'CONTENT_REJECTED', 'UNKNOWN_MODEL', 'VALIDATION_ERROR',
  'REFERENCE_NOT_SUPPORTED', 'RATE_LIMITED', 'PRUNA_NETWORK_ERROR', 'PRUNA_STATUS_ERROR', 'PRUNA_NO_CREDIT',
  'PRUNA_DOWNLOAD_ERROR', 'PRUNA_UPLOAD_ERROR', 'PRUNA_MISSING_STATUS', 'PRUNA_INVALID_ID',
  'PRUNA_ABORTED', 'UNKNOWN_PRUNA_MODEL', 'PRUNA_MODEL_CONFIG_ERROR', 'PRUNA_UNSAFE_URL',
  'PRUNA_UNSAFE_REDIRECT', 'PRUNA_UPLOAD_MISSING_URL',
  'SOUND_NOT_CONFIGURED', 'SOUND_BACKEND_ERROR', 'SOUND_INVALID_PATH',
  'SOUND_FIELD_TOO_LONG', 'SOUND_TIMEOUT', 'SOUND_NO_AUDIO',
  'INTERNAL_ERROR', 'UNKNOWN_ERROR',
] as const;
export type ErrorCode = (typeof ERROR_CODES)[number];
